--- |-
  my.greeting:Hello world from config server
  my.list.values:{"one',"two","three"}
  #my.db.values:connectionString-3243-foo
  db.connection:connectionString-3243-default-git-server db.host:127.0.0.1 db.port:1400
  
  management.endpoints.web.exposure.include:"*" spring.profile.active=test
